# See https://openmod.github.io/openmod-docs/development-guide/configuration/
PrintRPCCalls: true
# Emulates how Unturned will act once SteamChannels are removed while leaving Unturned calls in-tact
BlockManualRPCCalls: false